Metrics/LineLength:
  Enabled: false
Metrics/ClassLength:
  Max: 200
Metrics/MethodLength:
  Max: 20
Metrics/AbcSize:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/IndentHash:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/CaseEquality:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.4
